FROM nginx:latest

# Копируем конфигурацию Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем HTML файлы
COPY html/ /usr/share/nginx/html/




# Открываем порт 80
EXPOSE 80

    
#COPY certificate.pem /etc/nginx/certificate.pem
#COPY private_key.pem /etc/nginx/private_key.pem