# backend/Dockerfile
FROM golang:1.23

WORKDIR /backend

COPY . .

RUN go build -o main ./cmd/main.go

EXPOSE 8080

ENV MAILCODESEND=gleb.gleb.tula@mail.ru
ENV SMTPPASSWORD=H3AAtZjrdkEuqkchHMYu

CMD ["./main"]
