# backend/Dockerfile
FROM golang:1.23

WORKDIR /backend

COPY . .

RUN go build -o main ./cmd/main.go

EXPOSE 8080

ARG MAILCODESEND
ARG SMTPPASSWORD

# Установите переменные окружения
ENV MAILCODESEND=${MAILCODESEND}
ENV SMTPPASSWORD=${SMTPPASSWORD}

CMD ["./main"]
